# Generated by Django 4.2.4 on 2023-10-10 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotelapp', '0002_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.FileField(upload_to='productimages')),
            ],
        ),
    ]
